### ISSUE TITLE
Clippable Flags

### ISSUE THREAD

**Issue by abdallahmehiz** [arpitkatiyar1999/Country-Picker#6]
My app's design is rounded in almost all places, having the country flags being pointy or at right angles like this isn't ideal.
Is there a way to make the country flags have rounded corners?

**Comment by arpitkatiyar1999** [comment]
Hi @abdallahmehiz 

Thank you for your feedback regarding the design of the country flags. We understand that rounded corners would better match the overall style of your app.

While this feature isn’t available at the moment, we’re happy to share that it will be included in the next version of the library.

We appreciate your patience and look forward to enhancing your experience soon. Please let us know if you have any other suggestions.

**Comment by arpitkatiyar1999** [comment]
Hi @abdallahmehiz,  

Thank you once again for your valuable feedback regarding the design of country flags. We're excited to let you know that the feature to customize flag shapes is now available! 🎉  

You can now define the flag shape using the properties `CountriesListDialogDisplayProperties` and `SelectedCountryDisplayProperties`. This allows for complete flexibility in adapting the design to better match the style of your app.  

Additionally, please note that the **minimum supported version** has been updated from `1.2.1` to `1.3.0`.  

For a complete list of the new features and changes, please visit the release notes here:  
[Country Picker - GitHub Releases](https://github.com/arpitkatiyar1999/Country-Picker/releases)  

We hope these updates enhance your experience, and we’d love to hear any further suggestions you may have!

**Comment by abdallahmehiz** [comment]
Much appreciated
